# general configuration
url:
baseurl: '/hang-out-with-me'

# an avatar or logo (optional)
logo: "/images/logo.png"
title: "Hang Out With Me"
# tagline will appear under the title (optional)
tagline: ""

event:
  host: "Eton Doolittle"

encrypted_event: "6622e35372b9c785ed3878bf8b1a44fcd0248a115ec88d6a7c57e53a21287d23U2FsdGVkX19nwNvlQepx5syuG45ka/MnKNxLuNrA0yyJH4s4gmXDH9c1nkTD1ldA88WB8ga52/UUx8aDPJbXN0N43TFy2OQvS8WzmkvwAX0thdjKDA5Qn36W584Nfu9DP4+HW5woTzZ1fmatqBpdac6HeJhHCqU93wBX9/S0e02cYAlcUzSUKKyIaFfJ6Q+4voFh+BrpYVWDVKaj/AvWEjugc0mL9/Q3v8TV0jVEyVClbNXtQcQ2njWx29wGPGQA1IFcGWHcsm5bv14Usf3wHSFc8YuS+2dYCCnSSWOs5thBRaQEvKV458cOX45fMcyMPLqMLWISkjvfeLK6nAbn1Kyy00Rl0TyvQhCvnm1AasMfGEbXvkdzlxV7pu0q2y8AivvgZ8UkqtfIDjo3DVY3A0E1jil0Lpm/fbosoeHgR41Tt7sSvUbJQDwLB7M6Ic7350WE3t7lnvwCNHmM/QuXUTUmOpWV4/W8Gq1F+84kJxbSORIaD1PkFVS79ibuWFiorrXt/zVuDgzwHB0lLEzBbLVgmXGQg4iiCkXJk+xzx/Yk1yPdA7Fn+JphRP8lVtzEuVHnECQaY/a8KUq1D7jU8akco3orjcqaiKWPM3CaGVDBJbPp3RHtHsBWG2DipIrs/mpmThx8fzUiIFCKdEKWsDmdg5PN/AUA7L6ISKe3M6q+Gk3lDMg2whSMcaplnU5x0IM6DLLcjhZN6RJ0PVq8QoDI16tM0E3wMzm+/VGC2aUeA6++1xngnNAe6hc5Nor52h2TwmHOD1XRZa0fOOvcZWk7w7DhL8suxs0LIdjvVM8GxPvXn4Z9OJ4DBbBr3hIeAiXr7hQEuvyenmXEMi2HU/DuLaLHcl5fikdwgTpSkXUNdl2AAqqYxlkUPjlGy5Szw+8dvcXddhtuoXEhV2liPThZWNE79pcHKhXR2V0o7j/RsKsF+aNVomx5FezQxL4heU4RgTq2irjLWc8Fp56eFjJcMhg1kWzNqCUPIRDVaNgmjKFx3uAY69sdfjBgNo++E5Rfm0zo38VhThXwogxseJZvVgJUoKkQkqKAqS+THP11MIz9iTe97Kk12ADgikdVhiUek+zQJmO5xfnen6eEhJUIXhPJwIuCIgcq08SnyYuzkkv5GK/KXLZqvLczjfiqHz3iejELMzJuZNKdOcJcnLgUiK3S+OShe6gZbGDMzzJhAyyIaFS6PNtDlOJhsriuOwFdCvHhVeIJYwq0yWY0Tco3BpjBO92JwglSsjwbQjqE0izGjIX9ddKWj7uz0lXLZbwAzwsduyml5ukpCWdrSSjMR7m7jfARsIpN+X3Xy+ZYxtkoMKi2qVCTQ0TCEQCCbmh247DBgoMbHVrx1f7g7oVgCHPqCs3/RYX4wuc74S3WoKZoCxjBewGIApLuZz53lyP7ZXa+3BSzDDM/2DkOMtaICT37glTVQyiErvFTbpH5aEQtefRsJ1TDdlrScKaZL3igqbk1AkilaJN8TBgsCFXDzDeS0kZaZeoYVMQ4RR9iuMpR4mbfGvtNU5gdsE2XCYN2m2BodsXLIv7d3Dt2xBPMJVIZ4VYW335vBiXEl4NblRdJkLQW1h69fE+P0VsQHRjbJGDy29YCP22Qms+QOI1miL5tC/qpieM+E7YBibFBlFny+emV/g3ZkBzCyUR0lIAuDPhIW8xd2CWWABpAp1R+CT5uvVX7euq+kkB5Fh34pKMefLQqr/LKyNGjSp41ZxhPnCi6Bi/yt4Yaj03ntg1UYetsfH0/dtxOhHlsBD7sg084xNB552TNe8jugBoCcZxfCdZGr9ijcB17gWRKxw=="

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

exclude:
  - _events
  - gulpfile.js
  - README.md
  - .gitignore
  - .vscode
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - node_modules
